default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # We use environment variables for credentials —
  # never hardcode passwords in source code
  username: result_analyzer
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: result_analyzer_development

test:
  <<: *default
  database: result_analyzer_test

production:
  <<: *default
  database: result_analyzer_production
  username: result_analyzer
  password: <%= ENV["DATABASE_PASSWORD"] %>